development:
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  database: pixtory_development
  pool: 5
  username: pixtory
  password:

test:
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  database: pixtory_test
  username: pixtory
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: pixtory_production
  pool: 5
  username: pixtory
  password:
